######################################################################
##
## Filename: test_pwm_generator.udo
## Created on: Thu Nov 05 11:19:10 AM Iran Standard Time 2020
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
